### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by felixmariotto** [felixmariotto/chain-game#3]
- [ ] constrain camera movement with world colliders
- [ ] kinematic bodies meshes
- [ ] chain mesh/material
- [ ] player mesh
